version: '2.1'
services:
  mssql:
    image: mssql
    ports:
    - "1433:1433"
  amq:
    image: amq
    ports:
    - "61616:61616"   # Openwire
    - "61613:61613"
    - "1883:1883"
    - "8161:8161"     # web console
  component1:
    image: component-1
    ports:
    - "8080:8080"
  component2:
    image: component-2
    ports:
    - "8081:8080"
