version: '2.1'
services:
  mssql:
    image: mssql
    ports:
    - "1433:1433"
  amq:
    image: amq
    ports:
    - "61616:61616"   # Openwire
    - "61613:61613"
    - "1883:1883"
    - "8161:8161"     # web console
  component1:
    image: component-1
    ports:
    - "8080:8080"
    environment:
      ENVAR1: envar1
      ENVAR2: envar2
    depends_on: # required to start up database before services in most cases!
      amq:
        condition: service_started
      mssql:
        condition: service_healthy
  component2:
    image: component-2
    ports:
    - "8081:8080"
    environment:
      ENVAR1: envar1
      ENVAR2: envar2
    depends_on: # required to start up database before services in most cases!
      amq:
        condition: service_started
      mssql:
        condition: service_healthy
