parameters:

apiVersion: v1
kind: Template
metadata:
  name: notification-component
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: component-api
    namespace: openshiftprojectdv
    labels:
      app: notification-component
      component: component-api
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: component-worker
    namespace: openshiftprojectdv
    labels:
      app: notification-component
      component: component-worker
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: component-api
    namespace: openshiftprojectdv
    labels:
      app: notification-component
      component: component-api
  spec:
    failedBuildsHistoryLimit: 2
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: component-api:latest
    postCommit: {}
    completionDeadlineSeconds: 600
    resources:
      limits:
        cpu: 400m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 25Mi
    runPolicy: Serial
    source:
      git:
        ref: "master"
        uri: git@github.com:digipolisgent/java_service_component.git
      sourceSecret:
        name: digipolisgent-ci
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: ARTIFACT_DIR
          value: api/target
        - name: MAVEN_ARGS
          valueFrom:
            configMapKeyRef:
              key: MAVEN_ARGS
              name: dg-build-configmap
        - name: NEXUS_USER
          valueFrom:
            secretKeyRef: 
              name: dg-build-secrets
              key: NEXUS_USER
        - name: NEXUS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dg-build-secrets
              key: NEXUS_PASSWORD
        from:
          kind: ImageStreamTag
          name: openjdk18-openshift:latest
        pullSecret:
          name: imagestreamsecret
      type: Source
    successfulBuildsHistoryLimit: 2
    triggers: []
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: component-worker
    namespace: openshiftprojectdv
    labels:
      app: notification-component
      component: component-worker
  spec:
    failedBuildsHistoryLimit: 2
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: component-worker:latest
    postCommit: {}
    completionDeadlineSeconds: 600
    resources:
      limits:
        cpu: 400m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 25Mi
    runPolicy: Serial
    source:
      git:
        ref: "master"
        uri: git@github.com:digipolisgent/java_service_component.git
      sourceSecret:
        name: digipolisgent-ci
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: ARTIFACT_DIR
          value: api/target
        - name: MAVEN_ARGS
          valueFrom:
            configMapKeyRef:
              key: MAVEN_ARGS
              name: dg-build-configmap
        - name: NEXUS_USER
          valueFrom:
            secretKeyRef: 
              name: dg-build-secrets
              key: NEXUS_USER
        - name: NEXUS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dg-build-secrets
              key: NEXUS_PASSWORD
        from:
          kind: ImageStreamTag
          name: openjdk18-openshift:latest
        pullSecret:
          name: imagestreamsecret
      type: Source
    successfulBuildsHistoryLimit: 2
    triggers: []
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: component-api
    namespace: openshiftprojectdv
    labels:
      app: notification-component
      component: component-api
  spec:
    replicas: 1
    selector:
      app: notification-component
      component: component-api
    strategy:
      activeDeadlineSeconds: 660
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        name: component-api
        namespace: openshiftprojectdv
        labels:
          app: notification-component
          component: component-api
      spec:
        containers:
        - env:
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: component-secrets
                key: SPRING_DATASOURCE_PASSWORD
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom: 
              secretKeyRef:
                name: component-secrets
                key: SPRING_DATASOURCE_USERNAME
          - name: SPRING_ACTIVEMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: component-secrets
                key: SPRING_ACTIVEMQ_PASSWORD
          - name: SPRING_ACTIVEMQ_USER
            valueFrom:
              secretKeyRef:
                name: component-secrets
                key: SPRING_ACTIVEMQ_USER
          - name: SPRING_ACTIVEMQ_BROKER_URL
            value: ""
          - name: SPRING_ACTIVEMQ_POOL_ENABLED
            value: "true"
          - name: QUEUE_PREFIX
            value: businessdomaindv.notification-services.v1.component
          - name: QUEUE_CREATION
            value: creation
          - name: QUEUE_UPDATE
            value: update
          - name: QUEUE_ARCHIVE
            value: archive
          - name: QUEUE_COMPLETION
            value: completion
          - name: SPRING_DATASOURCE_URL
            value: ""
          - name: SPRING_PROFILES_ACTIVE
            value: "production"
          - name: "API_NAMESPACE_PREFIX"
            value: "businessdomain/component"
          - name: "APPLICATION_LOG_LEVEL"
            value: "INFO"
          - name: "SERVICE_MOCKING_ENABLED"
            value: "FALSE"
          image: docker-registry.default.svc:5000/openshiftprojectdv/component-api:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 30
            httpGet:
              path: /businessdomain/component/v2/status/am-i-up
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /businessdomain/component/v2/status/aggregate
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          name: component-api
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: 
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 25Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers: []
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: component-worker
    namespace: openshiftprojectdv
    labels:
      app: notification-component
      component: component-worker
  spec:
    replicas: 1
    selector:
      app: notification-component
      component: component-worker
    strategy:
      activeDeadlineSeconds: 660
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        name: component-worker
        namespace: openshiftprojectdv
        labels:
          app: notification-component
          component: component-worker
      spec:
        containers:
        - env:
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: component-secrets
                key: SPRING_DATASOURCE_PASSWORD
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom: 
              secretKeyRef:
                name: component-secrets
                key: SPRING_DATASOURCE_USERNAME
          - name: SPRING_ACTIVEMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: component-secrets
                key: SPRING_ACTIVEMQ_PASSWORD
          - name: SPRING_ACTIVEMQ_USER
            valueFrom:
              secretKeyRef:
                name: component-secrets
                key: SPRING_ACTIVEMQ_USER
          - name: SPRING_ACTIVEMQ_BROKER_URL
            value: ""
          - name: SPRING_ACTIVEMQ_POOL_ENABLED
            value: "true"
          - name: QUEUE_PREFIX
            value: businessdomaindv.notification-services.v1.component
          - name: QUEUE_CREATION
            value: creation
          - name: QUEUE_UPDATE
            value: update
          - name: QUEUE_ARCHIVE
            value: archive
          - name: QUEUE_COMPLETION
            value: completion
          - name: SPRING_DATASOURCE_URL
            value: ""
          - name: SPRING_PROFILES_ACTIVE
            value: "production"
          - name: "API_NAMESPACE_PREFIX"
            value: "businessdomain/component-worker"
          - name: "APPLICATION_LOG_LEVEL"
            value: "INFO"
          - name: "SERVICE_MOCKING_ENABLED"
            value: "FALSE"
          image: docker-registry.default.svc:5000/openshiftprojectdv/component-worker:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 30
            httpGet:
              path: /businessdomain/component-worker/v2/status/am-i-up
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /businessdomain/component-worker/v2/status/aggregate
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          name: component-worker
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: 
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 25Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers: []
- apiVersion: v1
  kind: Service
  metadata:
    name: component-api
    namespace: openshiftprojectdv
    labels:
      app: notification-component
      component: component-api
  spec:
    ports:
    - name: 8080
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: notification-component
      component: component-api
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: component-worker
    namespace: openshiftprojectdv
    labels:
      app: notification-component
      component: component-worker
  spec:
    ports:
    - name: 8080
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: notification-component
      component: component-worker
    sessionAffinity: None
    type: ClusterIP